language: node_js
node_js:
  - "lts/*"
script:
  - echo "Starting deploy"
install:
  - npm install -g firebase-tools
  - npm install -g vuepress
  - vuepress build
after_success:
  - firebase deploy --token $FIREBASE_DEPLOY_KEY